spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1014469081216-7p0mhad3dbet5507eupdpucfht0vn520.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          kakao:
            client-id: 03bbdf71352156f08fd91cdbd4b861e1
            client-name: Kakao
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: profile_nickname, account_email
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
            kakao:
              authorization_uri: https://kauth.kakao.com/oauth/authorize
              token_uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user_name_attribute: mummhy0811